cloud/sensing_bus/publisher/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/', views.about, name='about'),
    url(r'^visualize/', views.visualize, name='visualize'),
    url(r'^docs/',  views.docs, name='docs'),
    url(r'^measurements/$',views.measurement_list),
    ##Uncommenting the next line creates an unprotected url, good for testing
    #url(r'^measurements_batch/$',views.measurement_batch_list), 
    url(r'^measurements_batch_sec/$',views.measurement_batch_list),
    url(r'^measurements/(?P<pk>[0-9]+)/$', views.measurement_detail),
    url(r'^zip_measurements_batch_sec/$',views.zip_measurement_batch_list)
]

cloud/sensing_bus/sensing_bus/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets

# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    url(r'^', include('publisher.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

cloud/sensing_bus/publisher/models.py
from __future__ import unicode_literals
from django.db import models

class Bus(models.Model):
    """Represents a bus carrying a sensor node"""
    name = models.CharField(max_length=10, unique=True)

    def __unicode__(self):
        return self.name

class SensingNode(models.Model):
    """Represents a sensor node, from the Gathering layer"""
    bus = models.ForeignKey(Bus, on_delete=models.CASCADE,
         verbose_name="bus where the node is coupled", null=True, blank=True)
    def __unicode__(self):
        return "{}".format(self.pk)

class Stop(models.Model):
    """Represents a bus stop having a flushing node"""
    lat = models.DecimalField(max_digits=9, decimal_places=6)
    lng = models.DecimalField(max_digits=9, decimal_places=6)

    def __unicode__(self):
        return "{}, {}".format(self.lat, self.lng)


class Measurement(models.Model):
    """Represents the measurements made by a bus on a given time and place"""
    #Context of measurements
    created_on = models.DateTimeField(auto_now_add=True)
    bus = models.ForeignKey(Bus, on_delete=models.CASCADE,
             verbose_name="bus that collected measurement", null=True)
    node = models.ForeignKey(SensingNode, on_delete=models.CASCADE,
             verbose_name="node that collected measurement")
    stop = models.ForeignKey(Stop, on_delete=models.CASCADE,
             verbose_name="stop that received measurement")
    time = models.DateTimeField()
    lat = models.DecimalField(max_digits=9, decimal_places=6)
    lng = models.DecimalField(max_digits=9, decimal_places=6)

    #Measurements
    temperature = models.DecimalField(max_digits=4, decimal_places=1, null=True)
    humidity = models.DecimalField(max_digits=4, decimal_places=1, null=True)
    light = models.DecimalField(max_digits=5, decimal_places=1, null=True)
    rain = models.DecimalField(max_digits=5, decimal_places=1, null=True)

    def __unicode__(self):
        return "{}, {}, {}, {}".format(self.node, self.bus, self.stop, self.time)

cloud/sensing_bus/publisher/forms.py
import datetime
from django import forms


SENSORS = (('TEMPERATURE', u"Temperature"), ('HUMIDITY', u"Humidity"),
           ('LIGHT', u"Light"), ('RAIN', u"Rain"))

class VisualizeForm(forms.Form):
    bus_name = forms.CharField(label=u"Bus identifier", initial=u"A00000", max_length=10)
    start_time = forms.DateTimeField(label=u"Start time", initial=datetime.date.today, 
                                     widget=forms.Textarea(attrs={'type': 'date'}))
    end_time = forms.DateTimeField(label=u"End time", initial=datetime.date.today,
                                    widget=forms.Textarea(attrs={'type': 'date'}))
    sensor_name = forms.ChoiceField(widget=forms.RadioSelect(attrs={'type': 'radio'}),
                                    choices=SENSORS)
    min_lat = forms.DecimalField(label=u"Minimum Latitude", initial=0.0,
                                  min_value=(-90), max_value=90,
                                  max_digits=9, decimal_places=6)
    max_lat = forms.DecimalField(label=u"Maximum Latitude", initial=0.0,
                                  min_value=(-90), max_value=90,
                                  max_digits=9, decimal_places=6)
    min_lng = forms.DecimalField(label=u"Minimum Longitude", initial=0.0,
                                  min_value=(-180), max_value=180,
                                  max_digits=9, decimal_places=6)
    max_lng = forms.DecimalField(label=u"Maximum Longitude", initial=0.0,
                                  min_value=(-180), max_value=180,
                                  max_digits=9, decimal_places=6)

cloud/sensing_bus/publisher/views.py
from __future__ import unicode_literals
import json
import zlib
from datetime import datetime
from django.shortcuts import render
from django.http import HttpResponse
from publisher.models import Measurement
from publisher.models import Bus
from django.http import JsonResponse
from django.core.serializers.json import DjangoJSONEncoder
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import BaseParser 
from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser
from publisher.serializers import MeasurementSerializer
from publisher.serializers import MeasurementBatchList

from .forms import VisualizeForm

MAX_MEASURES = 500

def index(request):
    context = {}
    return render(request, 'publisher/index.html', context)

def about(request):
    context = {}
    return render(request, 'publisher/about.html', context)

def docs(request):
    context = {}
    return render(request, 'publisher/docs.html', context)

def visualize(request):
    """Renders the visualization webpage on GET and returns map data on POST"""
    form = VisualizeForm()
    context = {'form': form}

    if request.method == 'GET':
        return render(request, 'publisher/visualize.html', context)
    if request.method == 'POST':
        bus_name = request.POST.get("id_bus_name", "")
        min_lat = request.POST.get("id_min_lat", "")
        max_lat = request.POST.get("id_max_lat", "")
        min_lng = request.POST.get("id_min_lng", "")
        max_lng = request.POST.get("id_max_lng", "")
        start_time = request.POST.get("id_start_time", "")
        end_time = request.POST.get("id_end_time", "")
        sensor_name = request.POST.get("sensor_name", "")
        print "Sensor name = {}".format(sensor_name)

        q = Measurement.objects.all()
        if bus_name:
            bus_key = Bus.objects.filter(name__iexact=bus_name).first().pk
            q = q.filter(bus=bus_key)
        if min_lat:
            q = q.filter(lat__gte=min_lat)
        if max_lat:
            q = q.filter(lat__lte=max_lat)
        if min_lng:
            q = q.filter(lat__gte=min_lng)
        if max_lng:
            q = q.filter(lat__lte=max_lng)
        if start_time:
            q = q.filter(time__gte=datetime.strptime(start_time,
                                        "%m/%d/%Y %I:%M %p"))
        if end_time:
            q = q.filter(time__lte=datetime.strptime(end_time,
                                        "%m/%d/%Y %I:%M %p"))

        data = {'data' : []}
        values = []
        for o in q[:MAX_MEASURES]: #This value avoids that too many results overflow the browser
            d = {}
            d['bus'] = o.bus.name
            d['lat'] = float(o.lat)
            d['lng'] = float(o.lng)
            d['temperature'] = float(o.temperature)
            d['humidity'] = float(o.humidity)
            d['light'] = float(o.light)
            d['rain'] = float(o.rain)
            d['time'] = o.time
            if sensor_name.lower() == 'temperature':
                d['value'] = float(o.temperature)
                values.append(float(o.temperature))
            if sensor_name.lower() == 'humidity':
                d['value'] = float(o.humidity)
                values.append(float(o.humidity))
            if sensor_name.lower() == 'light':
                d['value'] = float(o.light)
                values.append(float(o.light))
            if sensor_name.lower() == 'rain':
                d['value'] = float(o.rain)
                values.append(float(o.rain))
            data['data'].append(d)


        data['max'] = max(values or [0])
        data['min'] = min(values or [0])
        #now = datetime.now()
        #html = "Data = %s" % data
        return JsonResponse(data)

    else:
        html = "<html><body>This is not nice, lek</body></html>"
        return HttpResponse(html)

class JSONResponse(HttpResponse):
    """
    An HttpResponse that renders its content into JSON.
    """
    def __init__(self, data, **kwargs):
        content = JSONRenderer().render(data)
        kwargs['content_type'] = 'application/json'
        super(JSONResponse, self).__init__(content, **kwargs)

class PlainTextParser(BaseParser):
    """
    A personalized parser to receive compressed data
    """

    media_type = 'text/plain'

    def parse(self, stream, media_type=None, parser_context=None):
        return stream.read()

@csrf_exempt
def measurement_list(request):
    """
    get:
    List all code measurements
    """
    if request.method == 'GET':
        bus_name = request.GET.get("bus_name", "")
        node_id = request.GET.get("node_id", "")
        min_lat = request.GET.get("min_lat", "")
        max_lat = request.GET.get("max_lat", "")
        min_lng = request.GET.get("min_lng", "")
        max_lng = request.GET.get("max_lng", "")
        start_time = request.GET.get("start_time", "")
        end_time = request.GET.get("end_time", "")

        q = Measurement.objects.all()[:MAX_MEASURES]

        if bus_name:
            bus_key = Bus.objects.filter(name__iexact=bus_name).first().pk
            q = q.filter(bus=bus_key)
        if node_id:
            q = q.filter(node=node_id)
        if min_lat:
            q = q.filter(lat__gte=min_lat)
        if max_lat:
            q = q.filter(lat__lte=max_lat)
        if min_lng:
            q = q.filter(lat__gte=min_lng)
        if max_lng:
            q = q.filter(lat__lte=max_lng)
        if start_time:
            q = q.filter(time__gte=datetime.strptime(start_time,
                                        "%Y-%m-%dT%H:%M:%S"))
        if end_time:
            q = q.filter(time__lte=datetime.strptime(end_time,
                                        "%Y-%m-%dT%H:%M:%S"))
        serializer = MeasurementSerializer(q, many=True)
        return JSONResponse(serializer.data)

    elif request.method == 'POST':
        html = "<html><body>This is not allowed. Use the url /measurements_batch_sec/ </body></html>"
        return HttpResponse(html)

@csrf_exempt
def measurement_detail(request, pk):
    """
    Retrieve, update or delete a code measurement.
    """
    try:
        measurement = Measurement.objects.get(pk=pk)
    except Measurement.DoesNotExist:
        return HttpResponse(status=404)

    if request.method == 'GET':
        serializer = MeasurementSerializer(measurement)
        return JSONResponse(serializer.data)

    elif request.method == 'PUT':
        data = JSONParser().parse(request)
        serializer = MeasurementSerializer(measurement, data=data)
        if serializer.is_valid(raise_exception=True):
            #serializer.save()
            return JSONResponse(serializer.data)
        return JSONResponse(serializer.errors, status=400)

    elif request.method == 'DELETE':
        measurement.delete()
        return HttpResponse(status=204)

@csrf_exempt
def measurement_batch_list(request):
    """
    List all code measurements batches, or create a new measurement batch.
    """
    if request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = MeasurementBatchList(data=data)
        if serializer.is_valid():
            print "Saving"
            serializer.save()
            return JSONResponse(serializer.data, status=201)
        return JSONResponse(serializer.errors, status=400)
    else:
        return JSONResponse({'msg':'Only POSTs allowed'},status=400)

@csrf_exempt
def zip_measurement_batch_list(request):
    """
    List all code measurements batches, or create a new measurement batch.
    """
    if request.method == 'POST':
        #request.data has the compressed data
        data = zlib.decompress(request.body)
        data = data.decode('zlib_codec').decode('utf-8')
        data = json.loads(data)
        #Now data is a JSON and can be serialized
        serializer = MeasurementBatchList(data=data)
        if serializer.is_valid():
            print "Saving"
            serializer.save()
            return JSONResponse(serializer.data, status=201)
        return JSONResponse(serializer.errors, status=400)
    else:
        return JSONResponse({'msg':'Only POSTs allowed'},status=400)

cloud/sensing_bus/publisher/templates/publisher/about.html
{% extends "base.html" %}

{% block title %}Beginning SensingBus Template{% endblock %}

{% block content %}

{% load static from staticfiles %}

<!--link rel="stylesheet" href="http://getbootstrap.com.vn/examples/equal-height-columns/equal-height-columns.css" /-->



<div class="col-md-8" id="welcome-pane">
  <h1>About SensingBus</h1>

  <p>SensingBus is a research project from the lab <a href="https://www.gta.ufrj.br">GTA</a>, from <a href="www.pee.ufrj.br/index.php/en/">Programa de Engenharia Elétrica</a> of Universidade Federal do Rio de Janeiro, in collaboration with <a href="http://www.pel.uerj.br/">Programa de Pós Graduação em Engenharia Elétrica</a>, from Universidade do Estado do Rio de Janeiro.</p>


  <h2>Team</h2>
  <div class="row row-eq-height">
    <div class="col-lg-2">
      <img src="{% static 'img/cruz.jpg' %}" class="img-circle" alt="cruz" height="80px" width="auto" vspace="10px" hspace="10px">
    </div>
    <div class="col-lg-10">
      <p><b>Pedro Cruz</b>: is pursuing his Doctor of Science degree in Electrical Engineering at UFRJ. His research interests include sensor networks and fog computing. Caminha has a Computing and Information Engineering degree from UFRJ.</p>
    </div>
  </div>
  <div class="row row-eq-height">
    <div class="col-lg-2">
      <img src="{% static 'img/silva.jpg' %}" class="img-circle" alt="silva" height="80px" width="auto" vspace="10px" hspace="10px">
    </div>
    <div class="col-lg-10">
      <p><b>Felipe F. da Silva</b>: is pursuing his Electronics and Computer Engineering degree at UFRJ. His research interests include cloud computing and network virtualization.</p>
    </div>
  </div>
  <div class="row row-eq-height">
    <div class="col-lg-2">
      <img src="{% static 'img/pacheco.jpg' %}" class="img-circle" alt="pacheco" height="80px" width="auto" vspace="10px" hspace="10px">
    </div>
    <div class="col-md-10">
      <p><b>Roberto G. Pacheco</b>: is pursuing his graduate degree in Electrical Engineering at UERJ. His research interests include computer networks, cloud computing and fog computing.</p>
    </div>
  </div>
  <div class="row row-eq-height">
    <div class="col-lg-2">
      <img src="{% static 'img/couto.png' %}" class="img-circle" alt="couto" height="80px" width="auto" vspace="10px" hspace="10px">
    </div>
    <div class="col-md-10">
      <p><b>Rodrigo S. Couto</b>: is an Associate Professor with Universidade do Estado do Rio de Janeiro (UERJ). His research interests include data center networks, cloud computing, network reliability, and network virtualization. Couto has a Doctor of Science degree in Electrical Engineering from Universidade Federal do Rio de Janeiro (UFRJ).</p>
    </div>
  </div>
  <div class="row row-eq-height">
    <div class="col-lg-2">
      <img src="{% static 'img/velloso.jpg' %}" class="img-circle" alt="velloso" height="80px" width="auto" vspace="10px" hspace="10px">
    </div>
    <div class="col-md-10">
      <p><b>Pedro B. Velloso</b>: is an Associate Professor with UFRJ. His research interests include routing, wireless networks, and future Internet. Velloso has a Doctor degree in Computer Science and Telecommunications from UPMC.</p>
    </div>
  </div>
  <div class="row row-eq-height">
    <div class="col-lg-2">
      <img src="{% static 'img/campista.jpg' %}" class="img-circle" alt="campista" height="80px" width="auto" vspace="10px" hspace="10px">
    </div>
    <div class="col-md-10">
      <p><b>Miguel Elias M. Campista</b>: is an Associate Professor with UFRJ. His research interests include wireless networking, cloud computing, and network science. Campista has a Doctor of Science degree in Electrical Engineering from UFRJ..</p>
    </div>
  </div>
  <div class="row row-eq-height">
    <div class="col-lg-2">
      <img src="{% static 'img/costa.png' %}" class="img-circle" alt="costa" height="80px" width="auto" vspace="10px" hspace="10px">
    </div>
    <div class="col-md-10">
      <p><b>Luís Henrique M. K. Costa</b>: is an Associate Professor with UFRJ. His research interests include routing, wireless networks, and future Internet. Costa has a Doctor degree in Computer Science from Université Pierre et Marie Curie (UPMC).</p>
    </div>
  </div>

  <h2>Acknowledgement</h2>
  <div class="row">
    <div class="col-md-12">
      <p><b>This project was funded by FAPERJ, CNPq and CAPES</b></p>
    </div>
  </div>


</div>

{% endblock %}

cloud/sensing_bus/publisher/templates/publisher/docs.html
{% extends "base.html" %}

{% block title %}Beginning SensingBus Template{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-8" id="welcome-pane">
  <h2>Welcome to SensingBus</h2>
  <p>These are the API endpoints offered by the Publishing node of SensingBus.</p>
  </div>
</div>

<script src="//google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>

<!--link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet"-->
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <div class="fancy-collapse-panel">
      <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
          <div class="panel-heading" role="tab" id="headingTwo">
            <h4 class="panel-title">
              <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">/measurements/
              </a>
            </h4>
          </div>
          <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
            <div class="panel-body">
              <h5>GET:</h5>
              <p>Returns a list with all the measurements that correspond to the filter.</p>
              <b>Parameters</b>
              <ul>
                <li><b>bus_name</b> <p>Defines a filter based on the name of the bus</p></li>
                <li><b>min_lat</b> <p>Defines a filter based on a minimum latitude</p></li>
                <li><b>max_lat</b> <p>Defines a filter based on a maximum latitude</p></li>
                <li><b>min_lng</b> <p>Defines a filter based on a minimum longitude</p></li>
                <li><b>max_lng</b> <p>Defines a filter based on a maximum longitude</p></li>
                <li><b>start_time</b> <p>Defines a filter based on a start time.</p><p>Should be in format "%Y-%m-%dT%H:%M:%S" (Example: 2017-04-07T16:23:00)</p></li>
                <li><b>end_time</b> <p>Defines a filter based on an end time</p><p>Should be in format "%Y-%m-%dT%H:%M:%S" (Example: 2017-04-07T16:23:00)</p></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading" role="tab" id="headingThree">
            <h4 class="panel-title">
              <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">/measurements_batch_sec/
              </a>
            </h4>
          </div>
          <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
            <div class="panel-body">
              <h5>POST:</h5>
              <p>Receives data and stores it into the database.</p>
              <p>This URL is protected. Only devices with recognized certificates are allowed to perform POSTs.</p>
              <p>A batch of measurements is expected.</p>
              <p><b>No parameters</b></p>
              <p><b>Payload example:</b></p>
              <p> <pre class="prettyprint">{
        "stop_id": 1,
        "batches": [{
                "node_id": 1,
                "type": "data",
                "received": "25081617154300",
                "header": "datetime,lat,lng,light,temperature,humidity,rain",
                "load": ["25081616493200,-22.865690,-43.223827,999,35.00,31.00,781",
                        "25081616493300,-22.865690,-43.223831,999,35.00,31.00,777",
                        "25081616493400,-22.865690,-43.223831,999,35.00,31.00,775",
                        "25081616493500,-22.865690,-43.223831,998,35.00,31.00,779",
                        "25081616493600,-22.865690,-43.223831,999,35.00,31.00,773",
                        "25081616493700,-22.865690,-43.223831,999,35.00,31.00,784",
                        "25081616493800,-22.865692,-43.223831,999,35.00,31.00,782",
                        "25081616493900,-22.865692,-43.223835,999,35.00,31.00,787",
                        "25081616494000,-22.865692,-43.223835,999,35.00,31.00,779",
                        "25081616494100,-22.865694,-43.223831,999,35.00,31.00,778",
                        "25081616494200,-22.865694,-43.223831,998,35.00,31.00,785",
                        "25081616494300,-22.865694,-43.223835,999,35.00,30.00,780",
                        "25081616494400,-22.865694,-43.223835,999,35.00,30.00,780"
                ]
        }, {
                "node_id": 2,
                "type": "data",
                "received": "25081617154300",
                "header": "datetime,lat,lng,light,temperature,humidity,rain",
                "load": ["25081616493200,-22.865690,-43.223827,999,35.00,31.00,781",
                        "25081616493300,-22.865690,-43.223831,999,35.00,31.00,777",
                        "25081616493400,-22.865690,-43.223831,999,35.00,31.00,775",
                        "25081616493500,-22.865690,-43.223831,998,35.00,31.00,779",
                        "25081616493600,-22.865690,-43.223831,999,35.00,31.00,773",
                        "25081616493700,-22.865690,-43.223831,999,35.00,31.00,784",
                        "25081616493800,-22.865692,-43.223831,999,35.00,31.00,782",
                        "25081616493900,-22.865692,-43.223835,999,35.00,31.00,787",
                        "25081616494000,-22.865692,-43.223835,999,35.00,31.00,779",
                        "25081616494100,-22.865694,-43.223831,999,35.00,31.00,778",
                        "25081616494200,-22.865694,-43.223831,998,35.00,31.00,785",
                        "25081616494300,-22.865694,-43.223835,999,35.00,30.00,780",
                        "25081616494400,-22.865694,-43.223835,999,35.00,30.00,780"
                ]
        }, {
                "node_id": 3,
                "type": "data",
                "received": "25081617154300",
                "header": "datetime,lat,lng,light,temperature,humidity,rain",
                "load": ["25081616493200,-22.865690,-43.223827,999,35.00,31.00,781",
                        "25081616493300,-22.865690,-43.223831,999,35.00,31.00,777",
                        "25081616493400,-22.865690,-43.223831,999,35.00,31.00,775",
                        "25081616493500,-22.865690,-43.223831,998,35.00,31.00,779",
                        "25081616493600,-22.865690,-43.223831,999,35.00,31.00,773",
                        "25081616493700,-22.865690,-43.223831,999,35.00,31.00,784",
                        "25081616493800,-22.865692,-43.223831,999,35.00,31.00,782",
                        "25081616493900,-22.865692,-43.223835,999,35.00,31.00,787",
                        "25081616494000,-22.865692,-43.223835,999,35.00,31.00,779",
                        "25081616494100,-22.865694,-43.223831,999,35.00,31.00,778",
                        "25081616494200,-22.865694,-43.223831,998,35.00,31.00,785",
                        "25081616494300,-22.865694,-43.223835,999,35.00,30.00,780",
                        "25081616494400,-22.865694,-43.223835,999,35.00,30.00,780"
                ]
        }]

}</pre></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- CONATINER END -->
{% endblock %}

cloud/sensing_bus/publisher/templates/publisher/visualize.html
{% extends "base.html" %}

{% load static from staticfiles %}
{% block title %}Beginning SensingBus Template{% endblock %}

{% block content %}

  <!-- Datetimepicker -->
  <script type="text/javascript" src="{% static 'js/moment.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>

  <link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}"/>

<div class ="container" style="height:87%; width:100%">
  <div class="row" style="height:100%; width:100%;">
    <div class="col-md-8" id="map" style="height:604px; width:700px;">
    </div>
    <div class="col-md-4 row-eq-height" id="welcome-pane">
      <div class="panel panel-primary">
        <!-- Default panel contents -->
        <div class="panel-heading">Search Measurements</div>
        <div class="panel-body" style="height: 563px;">
          <div class="form-group">

            <form id="visualization-search" method="POST" class="form-horizontal">
              {% csrf_token %}
              {{ form.non_field_errors }}
              {% for field in form %}


              <div class="form-group row">
                <label for="{{field.id_for_label}}" class="control-label col-xs-4">{{field.label}}</label>
                {% if not field.field.widget.attrs.type %}
                <div class="col-xs-8 ">
                  <input class="form-control" type="{{ field.field.widget.input_type }}" id="{{field.id_for_label}}" name="{{field.id_for_label}}" placeholder="{{field.initial}}" step="0.000001">
                </div>
                {% else %}
                  {% if field.field.widget.attrs.type == 'date' %}
                <div class="col-xs-8 input-group date" id="{{field.id_for_label}}" style="padding-left: 15px; padding-right: 15px;">
                  <input type="text" class="form-control" id="{{field.id_for_label}}" name="{{field.id_for_label}}" placeholder="{{field.initial}}"/>
                  <span class="input-group-addon">
                      <span class="glyphicon glyphicon-calendar"></span>
                  </span>
                </div>
                <!-- This script is here in order to be rendered by Django -->
                <script type="text/javascript">
                    $(function () {
                        $('#{{field.id_for_label}}').datetimepicker();
                    });
                </script>
                  {% endif %}
                  {% if field.field.widget.attrs.type == 'radio' %}
                <fieldset class="form-group">
                  <div class="col-xs-12 form-check">
                    <div>
                      <script type="text/javascript">
                        $(function(){

                          $(".dropdown-menu li").click(function(){

                            $("#sensor-list").html($(this).text()+ ' <span class="caret"></span>');
                            $("#sensor-list").val($(this).text());
                            console.log($(this).text());
                            $("#id_sensor_name").val($(this).text());

                         });

                        });
                      </script>
                      <input type="hidden" name="sensor_name" value="Temperature" id="id_sensor_name">
                      <button type="button" class="btn btn-default dropdown-toggle col-xs-12" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="sensor-list">
                      Temperature <span class="caret"></span>
                      </button>
                      <ul class="dropdown-menu dropdown-menu-center">
                      {% for option in field.field.choices %}
                        <li><a>{{option.1}}</a></li>
                      {% endfor %}
                      </ul>
                    </div>
                  </div>
                </fieldset>
                  {% endif %}
                {% endif %}
              </div>
              {% endfor %}

              <button class="btn btn-primary" type="submit" id="search-button">Search</button>
            </form>
          </div>
        </div>
      </div> <!-- End Panel -->
    </div>
  </div>
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <p>Submiting the form with no filters will show the results unfiltered</p>
      <p>Points on heatmap are responsive. Click them to view the measurements.</p>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>


<script
      src="https://maps.googleapis.com/maps/api/js?libraries=visualization">
</script>

<script type="text/javascript" src="{% static 'js/heatmap.js' %}"></script>
<script type="text/javascript" src="{% static 'js/gmaps-heatmap.js' %}"></script>


<script type="text/javascript" src="{% static 'js/visualize.js' %}"></script>

{% endblock %}